
title: Johir Uddin Sujon
url: 'http://johirsujon.github.io'
baseurl: '/test2' #change it according to your repository name



# Profile information
yourname: Johir Uddin  ## put your name
title: 'STUDENT &amp; WEB DEVELOPER'  ## your title
location: Dhaka Bangladesh


## Social Profiles
facebook: http://www.facebook.com/johir.uddin123  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
